DROP TABLE DOADOR;

CREATE TABLE DOADOR(NDOACOES INTEGER,TIPOSANGUINEODOADOR VARCHAR(10),NOMEDOADOR VARCHAR(40),SEXODOADOR VARCHAR(15),ID INTEGER PRIMARY KEY AUTOINCREMENT,DTULTIMADOACAO VARCHAR(15),EMAILDOADOR VARCHAR(30),TELEFONEDOADOR VARCHAR(15))